-- CIN.TECNICO definition
DROP TABLE TECNICO CASCADE CONSTRAINTS;
DROP TABLE VENDEDOR CASCADE CONSTRAINTS;
DROP TABLE USUARIOS CASCADE CONSTRAINTS;
DROP TABLE EMAIL CASCADE CONSTRAINTS;
DROP TABLE ENDERECO CASCADE CONSTRAINTS;
DROP TABLE COMPRADOR CASCADE CONSTRAINTS;
DROP TABLE LOJA CASCADE CONSTRAINTS;
DROP TABLE PRODUTO CASCADE CONSTRAINTS;
DROP TABLE COMPRAS CASCADE CONSTRAINTS;
DROP TABLE LISTA_DE_DESEJOS CASCADE CONSTRAINTS;

CREATE TABLE "TECNICO" 
   (	"ID" NUMBER(38,0), 
	"NOME" VARCHAR2(100), 
	"CPF" NUMBER(38,0), 
	"IDADE" NUMBER(38,0), 
	"ESPECIALIDADE" VARCHAR2(100), 
	 CONSTRAINT "TECNICO_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "TECNICO_UN" UNIQUE ("CPF")
  USING INDEX  ENABLE
   ) ;

-- CIN.USUARIOS definition

CREATE TABLE "USUARIOS" 
   (	"CPF" NUMBER(38,0), 
	"NOME" VARCHAR2(100), 
	"SEXO" CHAR(1), 
	"DATA_NASCIMENTO" DATE, 
	"QTD_INDICACOES" NUMBER(38,0), 
	"CPF_PADRINHO" NUMBER(38,0), 
	 CONSTRAINT "USUARIOS_PK" PRIMARY KEY ("CPF")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FK_USUARIOS" FOREIGN KEY ("CPF_PADRINHO")
	  REFERENCES "USUARIOS" ("CPF") ENABLE
   ) ;


-- CIN.EMAIL definition

CREATE TABLE "EMAIL" 
   (	"CPF" NUMBER(38,0), 
	"EMAIL" VARCHAR2(100), 
	 CONSTRAINT "EMAIL_PK" PRIMARY KEY ("CPF", "EMAIL")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FK_USUARIOS1" FOREIGN KEY ("CPF")
	  REFERENCES "USUARIOS" ("CPF") ENABLE
   ) ;


-- CIN.ENDERECO definition

CREATE TABLE "ENDERECO" 
   (	"CPF" NUMBER(38,0), 
	"RUA" VARCHAR2(100), 
	"BAIRRO" VARCHAR2(100), 
	"CEP" NUMBER(38,0), 
	 CONSTRAINT "ENDERECO_PK" PRIMARY KEY ("CPF", "RUA", "BAIRRO", "CEP")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FK_USUARIOS2" FOREIGN KEY ("CPF")
	  REFERENCES "USUARIOS" ("CPF") ENABLE
   ) ;



-- CIN.VENDEDOR definition

CREATE TABLE "VENDEDOR" 
   (	"CPF_USUARIO" NUMBER(38,0), 
	"DATA_ENTRADA" DATE, 
	"QTD_VENDAS" NUMBER(38,0), 
	 CONSTRAINT "VENDEDOR_PK" PRIMARY KEY ("CPF_USUARIO")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FK_USUARIOS3" FOREIGN KEY ("CPF_USUARIO")
	  REFERENCES "USUARIOS" ("CPF") ENABLE
   ) ;


-- CIN.COMPRADOR definition

CREATE TABLE "COMPRADOR" 
   (	"CPF_USUARIO" NUMBER(38,0), 
	"INTERESSES" VARCHAR2(100), 
	"QTD_COMPRAS" NUMBER(38,0), 
	 CONSTRAINT "COMPRADOR_PK" PRIMARY KEY ("CPF_USUARIO")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FK_USUARIOS4" FOREIGN KEY ("CPF_USUARIO")
	  REFERENCES "USUARIOS" ("CPF") ENABLE
   ) ;



-- CIN.LOJA definition

CREATE TABLE "LOJA" 
   (	"ID" NUMBER(38,0), 
	"CPF_VENDEDOR" NUMBER(38,0), 
	"NOME" VARCHAR2(100) NOT NULL ENABLE, 
	 CONSTRAINT "LOJA_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "LOJA_UN" UNIQUE ("NOME")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FK_VENDEDOR" FOREIGN KEY ("CPF_VENDEDOR")
	  REFERENCES "VENDEDOR" ("CPF_USUARIO") ENABLE
   ) ;

-- CIN.PRODUTO definition

CREATE TABLE "PRODUTO" 
   (	"ID" NUMBER(38,0), 
	"QUANTIDADE" NUMBER(38,0), 
	"PRECO" FLOAT(126), 
	"NOME" VARCHAR2(100), 
	"ID_LOJA" NUMBER(38,0), 
	 CONSTRAINT "PRODUTO_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FK_LOJA" FOREIGN KEY ("ID_LOJA")
	  REFERENCES "LOJA" ("ID") ENABLE
   ) ;

-- CIN.COMPRAS definition

CREATE TABLE "COMPRAS" 
   (	"CPF_COMPRADOR" NUMBER(38,0), 
	"ID_PRODUTO" NUMBER(38,0), 
	"HORARIO" TIMESTAMP (6), 
	"ID_TECNICO" NUMBER(38,0), 
	"QTD_PRODUTOS" NUMBER(38,0), 
	"QTD_PARCELAS" NUMBER(38,0), 
	"VALOR_PARCELAS" FLOAT(126), 
	"PRECO" FLOAT(126), 
	"JUROS" FLOAT(126), 
	 CONSTRAINT "COMPRAS_PK" PRIMARY KEY ("CPF_COMPRADOR", "ID_PRODUTO", "HORARIO")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FK_TECNICO" FOREIGN KEY ("ID_TECNICO")
	  REFERENCES "TECNICO" ("ID") ENABLE, 
	 CONSTRAINT "FK_PRODUTO" FOREIGN KEY ("ID_PRODUTO")
	  REFERENCES "PRODUTO" ("ID") ENABLE, 
	 CONSTRAINT "FK_COMPRADOR" FOREIGN KEY ("CPF_COMPRADOR")
	  REFERENCES "COMPRADOR" ("CPF_USUARIO") ENABLE
   ) ;

-- CIN.LISTA_DE_DESEJOS definition

CREATE TABLE "LISTA_DE_DESEJOS" 
   (	"CPF_COMPRADOR" NUMBER(38,0), 
	"ORDEM" NUMBER(38,0), 
	"NOME" VARCHAR2(100), 
	"QTD_ITENS" NUMBER(38,0), 
	 CONSTRAINT "LISTA_DE_DESEJOS_PK" PRIMARY KEY ("CPF_COMPRADOR", "ORDEM")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FK_COMPRADOR1" FOREIGN KEY ("CPF_COMPRADOR")
	  REFERENCES "COMPRADOR" ("CPF_USUARIO") ENABLE
   ) ;

-----------------------END-CRIACAO-----------------------

-- executar cinexpress_triggers.sql